=== NadaMohamed2243/ITI-Open-Source-Courses/open source/XML/DAY3/LAB/lab3part2/lab3.2(libValidationSchema)xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"/>

                <xs:element name="librarian">
                    <xs:complexType>
              
                            <xs:attribute name="name" type="xs:string" use="required"/>
                            <xs:attribute name="phone" type="xs:integer" use="required"/>
                            <xs:attribute name="gender" type="xs:string" use="optional" default="F">
                            </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                    
                                        <xs:element name="preface" type="xs:string"/>

                                        <xs:element name="parts">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="part">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="chapters">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                        
                                                                            <xs:element name="chapter">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="summary" type="xs:string"/>
																						<xs:element name="sections">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="section">
																										<xs:complexType>
																											<xs:sequence> 
																												<xs:element name="paragraphs">
																													<xs:complexType>
																														<xs:sequence>
																														    <xs:element name="paragraph"/>
																														</xs:sequence>
																													</xs:complexType>
																												</xs:element>
																											</xs:sequence>
																											<xs:attribute name="paragraphno" use="required">
																												<xs:simpleType>
																													<xs:restriction base="xs:integer">
																														<xs:minInclusive value="1"/>
																													</xs:restriction>
																												</xs:simpleType>
																											</xs:attribute>
																										</xs:complexType>
																									</xs:element>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																					
																					<xs:attribute name="title" use="required" type="xs:string"/>
																					<xs:attribute name="sectionsno" use="required">
																						<xs:simpleType>
																							<xs:restriction base="xs:integer">
																								<xs:minInclusive value="1"/>
																							</xs:restriction>
																						</xs:simpleType>
																					</xs:attribute>
																					
																				</xs:complexType>
                                                                            </xs:element>
                                                                            
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="title" type="xs:string" use="required"/>
                                                            <xs:attribute name="chapterno" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:integer">
                                                                        <xs:minInclusive value="1"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="bookref" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>

                                    <xs:attribute name="title" use="required" type="xs:string"/>
                                    <xs:attribute name="ISBN" use="required" type="xs:ID"/>
                                    <xs:attribute name="Author" use="required" type="xs:string"/>
                                    <xs:attribute name="partsno" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <xs:attribute name="location" type="xs:string" use="required"/>
            <xs:attribute name="bookno" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NadaMohamed2243/ITI-Open-Source-Courses/open source/XML/DAY3/LAB/lab3part2/lab3(library configuration file updates).xml
<?xml version="1.0" encoding="UTF-8"?>
<library location="mansoura" bookno="1000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\nadam\Downloads\open source\XML\DAY3\LAB\lab3part2\lab3.2(libValidationSchema)xsd.xsd">
	<description><![CDATA[Abig library at the center of the city & has beatiful veiw]]></description>
	<librarian name="nada" phone="01234" gender="F"/>
	<books>
		<book title="atomic habits" ISBN="A1234" Author="james clear" partsno="10">
			<preface><![CDATA[ 
				Atomic Habits: 
					An Easy & Proven Way to Build Good Habits
					& Break Bad Ones.
				This breakthrough book from James Clear is the most comprehensive 
				guide on how to change your habits and get 1% better every day.
			]]></preface>
			<parts>
				<part title="introduction" chapterno="30" bookref="A1234">
					<chapters>
						<chapter title="atomic habit ch 1" sectionsno="4">
							<summary><![CDATA[ 
								Atomic Habits c1: 
									An Easy & Proven Way to Build Good Habits
									& Break Bad Ones.
								This breakthrough book from James Clear is the most comprehensive 
								guide on how to change your habits and get 1% better every day.
							    ]]></summary>
							<sections>
								<section paragraphno="3">
									<paragraphs>
										<paragraph>this is paragraph1</paragraph>
									</paragraphs>
								</section>
							</sections>
						</chapter>
					</chapters>
				</part>
			</parts>
		</book>
	</books>
</library>
